export const operatorOptions = {
  EQ: {displayValue: 'equals'},
  NE: {displayValue: 'not equals'},
  LT: {displayValue: 'lower than'},
  LTE: {displayValue: 'lower than or eq'},
  GT: {displayValue: 'grater than'},
  GTE: {displayValue: 'grater than or eq'},
  CONTAINS: {displayValue: 'CONTAINS'},
  NOTCONTAINS: {displayValue: 'NOTCONTAINS'},
};
export const nameOptions = {
  LICENSE_KEY: {type: 'text', possibleValues: []},
  PLAYER_KEY: {type: 'text', possibleValues: []},
  IMPRESSION_ID: {type: 'text', possibleValues: []},
  USER_ID: {type: 'text', possibleValues: []},
  DOMAIN: {type: 'text', possibleValues: []},
  PATH: {type: 'text', possibleValues: []},
  LANGUAGE: {type: 'text', possibleValues: []},
  PLAYER_TECH: {type: 'text', possibleValues: ['html5, flash, native']},
  SCREEN_WIDTH: {type: 'number', possibleValues: []},
  SCREEN_HEIGHT: {type: 'number', possibleValues: []},
  IP_ADDRESS: {type: 'text', possibleValues: []},
  STREAM_FORMAT: {type: 'text', possibleValues: ['dash', 'hls', 'progressive']},
  PLAYER: {type: 'text', possibleValues: []},
  PLAYER_VERSION: {type: 'text', possibleValues: []},
  VIDEO_DURATION: {type: 'number', possibleValues: []},
  IS_LIVE: {type: 'boolean', possibleValues: [true, false]},
  IS_CASTING: {type: 'boolean', possibleValues: [true, false]},
  VIDEO_ID: {type: 'text', possibleValues: []},
  PLAYER_STARTUPTIME: {type: 'number', possibleValues: []},
  VIDEO_STARTUPTIME: {type: 'number', possibleValues: []},
  CUSTOM_USER_ID: {type: 'text', possibleValues: []},
  CLIENT_TIME: {type: 'number', possibleValues: []},
  SIZE: {type: 'text', possibleValues: ['WINDOW', 'FULLSCREEN']},
  VIDEO_WINDOW_WIDTH: {type: 'number', possibleValues: []},
  VIDEO_WINDOW_HEIGHT: {type: 'number', possibleValues: []},
  DROPPED_FRAMES: {type: 'number', possibleValues: []},
  PLAYED: {type: 'number', possibleValues: []},
  PAUSED: {type: 'number', possibleValues: []},
  BUFFERED: {type: 'number', possibleValues: []},
  AD: {type: 'number', possibleValues: []},
  SEEKED: {type: 'number', possibleValues: []},
  VIDEO_PLAYBACK_WIDTH: {type: 'number', possibleValues: []},
  VIDEO_PLAYBACK_HEIGHT: {type: 'number', possibleValues: []},
  VIDEO_BITRATE: {type: 'number', possibleValues: []},
  AUDIO_BITRATE: {type: 'number', possibleValues: []},
  VIDEOTIME_START: {type: 'number', possibleValues: []},
  VIDEOTIME_END: {type: 'number', possibleValues: []},
  DURATION: {type: 'number', possibleValues: []},
  STARTUPTIME: {type: 'number', possibleValues: []},
  BROWSER: {type: 'text', possibleValues: ['Chrome', 'Firefox', 'IE']},
  BROWSER_VERSION_MAJOR: {type: 'text', possibleValues: []},
  OPERATINGSYSTEM: {type: 'text', possibleValues: []},
  OPERATINGSYSTEM_VERSION_MAJOR: {type: 'text', possibleValues: []},
  DEVICETYPE: {type: 'text', possibleValues: []},
  COUNTRY: {type: 'text', possibleValues: []},
  REGION: {type: 'text', possibleValues: []},
  CITY: {type: 'text', possibleValues: []},
  CDN_PROVIDER: {type: 'text', possibleValues: []},
  MPD_URL: {type: 'text', possibleValues: []},
  M3U8_URL: {type: 'text', possibleValues: []},
  PROG_URL: {type: 'text', possibleValues: []},
  ERROR_CODE: {type: 'number', possibleValues: []},
  MINUTE: {type: 'number', possibleValues: []},
  HOUR: {type: 'number', possibleValues: []},
  DAY: {type: 'number', possibleValues: []},
  MONTH: {type: 'number', possibleValues: []},
  PAGE_LOAD_TIME: {type: 'number', possibleValues: []},
  PAGE_LOAD_TYPE: {type: 'number', possibleValues: [1, 2, 3]},
};
